// Code generated by protoc-gen-go. DO NOT EDIT.
// versions:
// 	protoc-gen-go v1.36.10
// 	protoc        v6.32.1
// source: v1/alarm.proto

package alarm

import (
	reflect "reflect"
	sync "sync"
	unsafe "unsafe"

	protoreflect "google.golang.org/protobuf/reflect/protoreflect"
	protoimpl "google.golang.org/protobuf/runtime/protoimpl"
	timestamppb "google.golang.org/protobuf/types/known/timestamppb"
)

const (
	// Verify that this generated code is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(20 - protoimpl.MinVersion)
	// Verify that runtime/protoimpl is sufficiently up-to-date.
	_ = protoimpl.EnforceVersion(protoimpl.MaxVersion - 20)
)

// SystemActor identifies who performed an action in the system.
// This provides audit trails and accountability for alarm operations.
type SystemActor struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Hostname      string                 `protobuf:"bytes,1,opt,name=hostname,proto3" json:"hostname,omitempty"` // The machine where the action originated
	Username      string                 `protobuf:"bytes,2,opt,name=username,proto3" json:"username,omitempty"` // The OS user who initiated the action
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SystemActor) Reset() {
	*x = SystemActor{}
	mi := &file_v1_alarm_proto_msgTypes[0]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SystemActor) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SystemActor) ProtoMessage() {}

func (x *SystemActor) ProtoReflect() protoreflect.Message {
	mi := &file_v1_alarm_proto_msgTypes[0]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SystemActor.ProtoReflect.Descriptor instead.
func (*SystemActor) Descriptor() ([]byte, []int) {
	return file_v1_alarm_proto_rawDescGZIP(), []int{0}
}

func (x *SystemActor) GetHostname() string {
	if x != nil {
		return x.Hostname
	}
	return ""
}

func (x *SystemActor) GetUsername() string {
	if x != nil {
		return x.Username
	}
	return ""
}

// SetAlarmStateRequest is used to change the alarm's active/inactive state.
type SetAlarmStateRequest struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Actor         *SystemActor           `protobuf:"bytes,1,opt,name=actor,proto3" json:"actor,omitempty"`                           // Who is changing the state
	IsEnabled     bool                   `protobuf:"varint,2,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"` // True to activate, false to deactivate
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *SetAlarmStateRequest) Reset() {
	*x = SetAlarmStateRequest{}
	mi := &file_v1_alarm_proto_msgTypes[1]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *SetAlarmStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*SetAlarmStateRequest) ProtoMessage() {}

func (x *SetAlarmStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_alarm_proto_msgTypes[1]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use SetAlarmStateRequest.ProtoReflect.Descriptor instead.
func (*SetAlarmStateRequest) Descriptor() ([]byte, []int) {
	return file_v1_alarm_proto_rawDescGZIP(), []int{1}
}

func (x *SetAlarmStateRequest) GetActor() *SystemActor {
	if x != nil {
		return x.Actor
	}
	return nil
}

func (x *SetAlarmStateRequest) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

// GetAlarmStateRequest asks for the current alarm status.
type GetAlarmStateRequest struct {
	state           protoimpl.MessageState `protogen:"open.v1"`
	RequestingActor *SystemActor           `protobuf:"bytes,1,opt,name=requesting_actor,json=requestingActor,proto3" json:"requesting_actor,omitempty"` // Who is checking the status
	unknownFields   protoimpl.UnknownFields
	sizeCache       protoimpl.SizeCache
}

func (x *GetAlarmStateRequest) Reset() {
	*x = GetAlarmStateRequest{}
	mi := &file_v1_alarm_proto_msgTypes[2]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *GetAlarmStateRequest) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*GetAlarmStateRequest) ProtoMessage() {}

func (x *GetAlarmStateRequest) ProtoReflect() protoreflect.Message {
	mi := &file_v1_alarm_proto_msgTypes[2]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use GetAlarmStateRequest.ProtoReflect.Descriptor instead.
func (*GetAlarmStateRequest) Descriptor() ([]byte, []int) {
	return file_v1_alarm_proto_rawDescGZIP(), []int{2}
}

func (x *GetAlarmStateRequest) GetRequestingActor() *SystemActor {
	if x != nil {
		return x.RequestingActor
	}
	return nil
}

// AlarmStateResponse provides the complete current state of the alarm system.
type AlarmStateResponse struct {
	state         protoimpl.MessageState `protogen:"open.v1"`
	Timestamp     *timestamppb.Timestamp `protobuf:"bytes,1,opt,name=timestamp,proto3" json:"timestamp,omitempty"`                   // When this state was recorded
	LastActor     *SystemActor           `protobuf:"bytes,2,opt,name=last_actor,json=lastActor,proto3" json:"last_actor,omitempty"`  // Who last changed the state
	IsEnabled     bool                   `protobuf:"varint,3,opt,name=is_enabled,json=isEnabled,proto3" json:"is_enabled,omitempty"` // Current alarm status (on/off)
	unknownFields protoimpl.UnknownFields
	sizeCache     protoimpl.SizeCache
}

func (x *AlarmStateResponse) Reset() {
	*x = AlarmStateResponse{}
	mi := &file_v1_alarm_proto_msgTypes[3]
	ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
	ms.StoreMessageInfo(mi)
}

func (x *AlarmStateResponse) String() string {
	return protoimpl.X.MessageStringOf(x)
}

func (*AlarmStateResponse) ProtoMessage() {}

func (x *AlarmStateResponse) ProtoReflect() protoreflect.Message {
	mi := &file_v1_alarm_proto_msgTypes[3]
	if x != nil {
		ms := protoimpl.X.MessageStateOf(protoimpl.Pointer(x))
		if ms.LoadMessageInfo() == nil {
			ms.StoreMessageInfo(mi)
		}
		return ms
	}
	return mi.MessageOf(x)
}

// Deprecated: Use AlarmStateResponse.ProtoReflect.Descriptor instead.
func (*AlarmStateResponse) Descriptor() ([]byte, []int) {
	return file_v1_alarm_proto_rawDescGZIP(), []int{3}
}

func (x *AlarmStateResponse) GetTimestamp() *timestamppb.Timestamp {
	if x != nil {
		return x.Timestamp
	}
	return nil
}

func (x *AlarmStateResponse) GetLastActor() *SystemActor {
	if x != nil {
		return x.LastActor
	}
	return nil
}

func (x *AlarmStateResponse) GetIsEnabled() bool {
	if x != nil {
		return x.IsEnabled
	}
	return false
}

var File_v1_alarm_proto protoreflect.FileDescriptor

const file_v1_alarm_proto_rawDesc = "" +
	"\n" +
	"\x0ev1/alarm.proto\x12\falarm.button\x1a\x1fgoogle/protobuf/timestamp.proto\"E\n" +
	"\vSystemActor\x12\x1a\n" +
	"\bhostname\x18\x01 \x01(\tR\bhostname\x12\x1a\n" +
	"\busername\x18\x02 \x01(\tR\busername\"f\n" +
	"\x14SetAlarmStateRequest\x12/\n" +
	"\x05actor\x18\x01 \x01(\v2\x19.alarm.button.SystemActorR\x05actor\x12\x1d\n" +
	"\n" +
	"is_enabled\x18\x02 \x01(\bR\tisEnabled\"\\\n" +
	"\x14GetAlarmStateRequest\x12D\n" +
	"\x10requesting_actor\x18\x01 \x01(\v2\x19.alarm.button.SystemActorR\x0frequestingActor\"\xa7\x01\n" +
	"\x12AlarmStateResponse\x128\n" +
	"\ttimestamp\x18\x01 \x01(\v2\x1a.google.protobuf.TimestampR\ttimestamp\x128\n" +
	"\n" +
	"last_actor\x18\x02 \x01(\v2\x19.alarm.button.SystemActorR\tlastActor\x12\x1d\n" +
	"\n" +
	"is_enabled\x18\x03 \x01(\bR\tisEnabled2\xbc\x01\n" +
	"\fAlarmService\x12U\n" +
	"\rSetAlarmState\x12\".alarm.button.SetAlarmStateRequest\x1a .alarm.button.AlarmStateResponse\x12U\n" +
	"\rGetAlarmState\x12\".alarm.button.GetAlarmStateRequest\x1a .alarm.button.AlarmStateResponseB.Z,github.com/oshokin/alarm-button/api/v1;alarmb\x06proto3"

var (
	file_v1_alarm_proto_rawDescOnce sync.Once
	file_v1_alarm_proto_rawDescData []byte
)

func file_v1_alarm_proto_rawDescGZIP() []byte {
	file_v1_alarm_proto_rawDescOnce.Do(func() {
		file_v1_alarm_proto_rawDescData = protoimpl.X.CompressGZIP(unsafe.Slice(unsafe.StringData(file_v1_alarm_proto_rawDesc), len(file_v1_alarm_proto_rawDesc)))
	})
	return file_v1_alarm_proto_rawDescData
}

var file_v1_alarm_proto_msgTypes = make([]protoimpl.MessageInfo, 4)
var file_v1_alarm_proto_goTypes = []any{
	(*SystemActor)(nil),           // 0: alarm.button.SystemActor
	(*SetAlarmStateRequest)(nil),  // 1: alarm.button.SetAlarmStateRequest
	(*GetAlarmStateRequest)(nil),  // 2: alarm.button.GetAlarmStateRequest
	(*AlarmStateResponse)(nil),    // 3: alarm.button.AlarmStateResponse
	(*timestamppb.Timestamp)(nil), // 4: google.protobuf.Timestamp
}
var file_v1_alarm_proto_depIdxs = []int32{
	0, // 0: alarm.button.SetAlarmStateRequest.actor:type_name -> alarm.button.SystemActor
	0, // 1: alarm.button.GetAlarmStateRequest.requesting_actor:type_name -> alarm.button.SystemActor
	4, // 2: alarm.button.AlarmStateResponse.timestamp:type_name -> google.protobuf.Timestamp
	0, // 3: alarm.button.AlarmStateResponse.last_actor:type_name -> alarm.button.SystemActor
	1, // 4: alarm.button.AlarmService.SetAlarmState:input_type -> alarm.button.SetAlarmStateRequest
	2, // 5: alarm.button.AlarmService.GetAlarmState:input_type -> alarm.button.GetAlarmStateRequest
	3, // 6: alarm.button.AlarmService.SetAlarmState:output_type -> alarm.button.AlarmStateResponse
	3, // 7: alarm.button.AlarmService.GetAlarmState:output_type -> alarm.button.AlarmStateResponse
	6, // [6:8] is the sub-list for method output_type
	4, // [4:6] is the sub-list for method input_type
	4, // [4:4] is the sub-list for extension type_name
	4, // [4:4] is the sub-list for extension extendee
	0, // [0:4] is the sub-list for field type_name
}

func init() { file_v1_alarm_proto_init() }
func file_v1_alarm_proto_init() {
	if File_v1_alarm_proto != nil {
		return
	}
	type x struct{}
	out := protoimpl.TypeBuilder{
		File: protoimpl.DescBuilder{
			GoPackagePath: reflect.TypeOf(x{}).PkgPath(),
			RawDescriptor: unsafe.Slice(unsafe.StringData(file_v1_alarm_proto_rawDesc), len(file_v1_alarm_proto_rawDesc)),
			NumEnums:      0,
			NumMessages:   4,
			NumExtensions: 0,
			NumServices:   1,
		},
		GoTypes:           file_v1_alarm_proto_goTypes,
		DependencyIndexes: file_v1_alarm_proto_depIdxs,
		MessageInfos:      file_v1_alarm_proto_msgTypes,
	}.Build()
	File_v1_alarm_proto = out.File
	file_v1_alarm_proto_goTypes = nil
	file_v1_alarm_proto_depIdxs = nil
}
